### ISSUE TITLE
Book for this course?

### ISSUE THREAD

**Issue by TheFern2** [zhengnengchen/CSCI-1200-Data-Structure#6]
Hi @zhengnengchen 

I am looking to do the labs and exercises on my own, do you happen to remember which book(s) were used for this class?

**Comment by zhengnengchen** [comment]
Hi @TheFern2 We didn’t have a specific textbook. The only course material we could rely on was the handouts you would get for each lecture conducted in DCC 308.

You would not have major problems with data structure itself if you attend every lecture. The most time-consuming part was debugging with C++. It might be helpful if you do your own research on StackOverflow first and organized a list of questions that you could not find the answers in handouts or on the internet to TA sessions.

Good luck with your CSCI-1200!

**Comment by TheFern2** [comment]
Thank you @zhengnengchen I am not attending school, just some self learning for CSCI 4976 https://github.com/RPISEC/Malware, I noticed there were some prereqs CSCI-2500 had a book, so I figured this one too, but if I can follow just the handouts, then is even better.  Thanks for your fast response!
